"""
fin_parser/extraction/claude_extractor.py
Phase 1 extraction: parse filing HTML, chunk it, send to Claude, get structured metrics back.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import anthropic
import pdfplumber

from fin_parser.config import ANTHROPIC_API_KEY, CLAUDE_MODEL

CLIENT = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

METRICS_TO_EXTRACT = [
    "revenue", "net_income", "eps_basic", "eps_diluted",
    "free_cash_flow", "operating_cash_flow", "shares_outstanding",
    "shares_diluted", "total_debt", "cash_and_equivalents", "goodwill", "capex",
]

SYSTEM_PROMPT = """
You are a financial analyst extracting data from SEC 10-K and 10-Q filings.
You will be given a section of a filing. Extract ONLY the metrics below and return a valid JSON object.
No preamble, no explanation, no markdown — just the JSON.

METRIC DEFINITIONS (be precise about which line item to use):

Income Statement:
- revenue: "Net sales" or "Total net revenue" — the top-line revenue figure. Do NOT use segment
  revenues that sum to a larger total. Use the single consolidated top-line figure.
- net_income: "Net income" attributable to the company (not including minority interest).
- eps_basic: "Basic" earnings per share as reported.
- eps_diluted: "Diluted" earnings per share as reported.

Cash Flow Statement:
- operating_cash_flow: "Net cash generated by operating activities" or equivalent.
- capex: "Payments for acquisition of property, plant and equipment" — always return as a
  POSITIVE number even if shown as negative in the filing.
- free_cash_flow: operating_cash_flow minus capex. Compute this yourself if both are present.

Balance Sheet:
- cash_and_equivalents: "Cash and cash equivalents" only — do NOT include marketable securities.
- total_debt: Sum of "Term debt, current portion" + "Term debt, non-current" (long-term debt).
  Do NOT include lease obligations or accounts payable.
- goodwill: "Goodwill" as reported on the balance sheet.

Share Data:
- shares_outstanding: Basic weighted-average shares used in EPS calculation (in millions).
- shares_diluted: Diluted weighted-average shares used in EPS calculation (in millions).

RULES:
- All monetary values in millions of USD. If the filing reports in thousands, divide by 1000.
  If reported in billions, multiply by 1000.
- Share counts in millions.
- EPS in dollars as reported — do not scale.
- Use ONLY the most recent fiscal year / annual period if multiple years are shown.
- If a metric cannot be found in this chunk, set it to null.
- Never guess or estimate — only extract values explicitly stated in the text.

OUTPUT FORMAT (return exactly this structure):
{
  "revenue": 391035,
  "net_income": 93736,
  "eps_basic": 6.14,
  "eps_diluted": 6.11,
  "free_cash_flow": 99584,
  "operating_cash_flow": 110543,
  "shares_outstanding": 15439,
  "shares_diluted": 15550,
  "total_debt": 95281,
  "cash_and_equivalents": 29965,
  "goodwill": 72609,
  "capex": 10959
}
""".strip()


def extract_text_from_htm(path: Path) -> str:
    """
    Strip HTML tags from a filing and return plain text.
    Preserves table structure by inserting tabs/newlines around cells.
    """
    raw = path.read_text(encoding="utf-8", errors="ignore")

    # Remove scripts and styles
    raw = re.sub(r"<script[^>]*>.*?</script>", " ", raw, flags=re.DOTALL | re.IGNORECASE)
    raw = re.sub(r"<style[^>]*>.*?</style>", " ", raw, flags=re.DOTALL | re.IGNORECASE)

    # Preserve table structure
    raw = re.sub(r"<tr[^>]*>", "\n", raw, flags=re.IGNORECASE)
    raw = re.sub(r"</tr>", "\n", raw, flags=re.IGNORECASE)
    raw = re.sub(r"<td[^>]*>|<th[^>]*>", "\t", raw, flags=re.IGNORECASE)
    raw = re.sub(r"</td>|</th>", "", raw, flags=re.IGNORECASE)

    # Preserve paragraph/block breaks
    raw = re.sub(r"<br[^>]*>", "\n", raw, flags=re.IGNORECASE)
    raw = re.sub(r"</p>|</div>|</h[1-6]>", "\n", raw, flags=re.IGNORECASE)

    # Remove remaining tags
    text = re.sub(r"<[^>]+>", "", raw)

    # Decode common HTML entities
    text = text.replace("&#8220;", '"').replace("&#8221;", '"')
    text = text.replace("&#8217;", "'").replace("&#8216;", "'")
    text = text.replace("&amp;", "&").replace("&nbsp;", " ")
    text = text.replace("&#160;", " ").replace("&lt;", "<").replace("&gt;", ">")

    # Collapse excessive whitespace but preserve newlines
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{4,}", "\n\n\n", text)

    return text.strip()


def find_financial_section(text: str) -> str:
    """
    Isolate the actual financial statements — skips TOC, risk factors,
    and the auditor report by finding the first real data table after
    the section heading.
    """
    text_upper = text.upper()
    # Risk factors and TOC are in the first ~40% — skip them
    search_start = int(len(text) * 0.40)

    markers = [
        "CONSOLIDATED STATEMENTS OF OPERATIONS",
        "CONSOLIDATED STATEMENTS OF INCOME",
        "CONSOLIDATED BALANCE SHEET",
        "CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME",
        "NOTES TO CONSOLIDATED FINANCIAL STATEMENTS",
        "F-1",
    ]

    best_pos = len(text)
    for marker in markers:
        pos = text_upper.find(marker, search_start)
        if 0 < pos < best_pos:
            best_pos = pos

    if best_pos >= len(text):
        return text[int(len(text) * 0.60):]

    # We found the section heading — now skip past auditor report / mini-TOC
    # by finding the first line that contains an actual dollar amount or number
    # within 50k chars of the heading
    candidate = text[best_pos: best_pos + 50_000]
    lines = candidate.split("\n")
    data_start_offset = 0
    seen_years = False
    for i, line in enumerate(lines):
        stripped = line.strip()
        # Look for a year header like "2025 2024 2023"
        if re.search(r"20\d\d\s+20\d\d", stripped):
            seen_years = True
        # After seeing years, find first line with a dollar amount
        if seen_years and re.search(r"\$\s*[\d,]+|	\s*[\d,]+", stripped):
            data_start_offset = sum(len(l) + 1 for l in lines[:i])
            break

    return text[best_pos + data_start_offset: best_pos + data_start_offset + 120_000]


def chunk_text(text: str, chunk_size: int = 12_000, overlap: int = 500) -> list[str]:
    """Split text into overlapping chunks to stay within Claude's context."""
    chunks = []
    start = 0
    while start < len(text):
        end = start + chunk_size
        chunks.append(text[start:end])
        start = end - overlap
    return chunks


def extract_metrics_from_chunk(chunk: str) -> dict[str, Any]:
    """Send one chunk to Claude and return parsed metrics dict."""
    response = CLIENT.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=1000,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": chunk}],
    )
    raw = response.content[0].text.strip()
    raw = re.sub(r"^```json\s*", "", raw)
    raw = re.sub(r"\s*```$", "", raw)
    return json.loads(raw)


def merge_metrics(results: list[dict[str, Any]]) -> dict[str, Any]:
    """Merge metrics across chunks — take first non-null value for each metric."""
    merged: dict[str, Any] = {m: None for m in METRICS_TO_EXTRACT}
    for result in results:
        for metric in METRICS_TO_EXTRACT:
            if merged[metric] is None and result.get(metric) is not None:
                merged[metric] = result[metric]
    return merged


# Patterns used to detect reporting-unit declarations. They live at module
# scope so `detect_reporting_unit` stays cheap to call and so tests can
# inspect them. Each list is a set of regex fragments that will match after
# whitespace has been stripped from the input — pdfplumber frequently
# collapses spaces in PDF table headers (e.g. "(thousandsofUnitedStatesdollars)"
# rather than "(thousands of United States dollars)"), so matching against a
# compacted copy of the text is far more reliable than the original.
_THOUSANDS_MARKERS = [
    r"\(inthousands\)",
    r"amountsinthousands",
    r"inthousandsof(unitedstates|u\.?s\.?|canadian|c\$|us\$)?dollars",
    r"\(thousandsofunitedstatesdollars",
    r"\(thousandsofcanadiandollars",
    r"\(thousandsofusdollars",
    r"\(thousandsofu\.s\.dollars",
    r"expressedinthousands",
]
_MILLIONS_MARKERS = [
    r"\(inmillions\)",
    r"amountsinmillions",
    r"inmillionsof(unitedstates|u\.?s\.?|canadian|c\$|us\$)?dollars",
    r"\(millionsofunitedstatesdollars",
    r"\(millionsofcanadiandollars",
    r"\(millionsofusdollars",
    r"\(millionsofu\.s\.dollars",
    r"expressedinmillions",
]


def detect_reporting_unit(text: str, override: str | None = None) -> str:
    """
    Decide whether monetary values in the filing are reported in thousands
    or millions, and return a hint string that gets prepended to every
    chunk sent to Claude.

    Scans the WHOLE document (not just the first 5k chars) because
    Canadian IFRS interim reports declare units in the repeated table
    headers rather than the cover page, and those headers often appear
    80k+ characters into the PDF. Matches are counted; the higher count
    wins. Ties fall through to an 'ambiguous' hint that asks Claude to
    decide per-table.

    Args:
        text:     full document text
        override: optional 'thousands' | 'millions' — bypasses detection
                  entirely. Exposed as a CLI escape hatch for the rare
                  filing whose unit declaration the regex misses.
    """
    if override:
        o = override.strip().lower()
        if o in {"thousands", "thousand", "k", "000s"}:
            return (
                "NOTE: The user explicitly declared this filing reports monetary "
                "values in THOUSANDS of USD. Divide all monetary values from "
                "tables by 1000 to convert to millions before returning."
            )
        if o in {"millions", "million", "m", "mm", "000000s"}:
            return (
                "NOTE: The user explicitly declared this filing reports "
                "monetary values in MILLIONS of USD. No conversion needed."
            )
        # Unknown override keyword — fall through to autodetect.

    compact = re.sub(r"\s+", "", text).lower()
    thousands_hits = sum(len(re.findall(p, compact)) for p in _THOUSANDS_MARKERS)
    millions_hits  = sum(len(re.findall(p, compact)) for p in _MILLIONS_MARKERS)

    if thousands_hits > millions_hits:
        return (
            f"NOTE: This filing reports monetary values in THOUSANDS of USD "
            f"(detected {thousands_hits} 'thousands' unit declarations vs "
            f"{millions_hits} 'millions'). Divide all monetary values from "
            f"tables by 1000 to convert to millions before returning. "
            f"IMPORTANT: ignore inline MD&A prose like '$1,055 million' — "
            f"use the TABLE headers as ground truth since the tables are "
            f"where the extracted values come from."
        )
    if millions_hits > thousands_hits:
        return (
            f"NOTE: This filing reports monetary values in MILLIONS of USD "
            f"(detected {millions_hits} 'millions' unit declarations vs "
            f"{thousands_hits} 'thousands'). No conversion needed."
        )
    return (
        f"NOTE: Reporting unit ambiguous — found {thousands_hits} 'thousands' "
        f"and {millions_hits} 'millions' declarations. Look for '(in thousands)' "
        f"or '(in millions)' adjacent to each financial table you read and "
        f"scale accordingly. Convert all monetary values to millions of USD."
    )


def extract_text_from_pdf(path: Path) -> str:
    """
    Extract text from a PDF using pdfplumber. Page breaks are preserved
    as `\\n\\n--- PAGE N ---\\n\\n` markers so Claude can see structure
    when reasoning about multi-page tables. Canadian issuers file
    quarterly MD&A and interim financials as PDFs on SEDAR+, so this is
    the entry point for any non-mining Canadian filing.
    """
    pieces: list[str] = []
    with pdfplumber.open(path) as pdf:
        for i, page in enumerate(pdf.pages, start=1):
            text = page.extract_text() or ""
            pieces.append(f"\n\n--- PAGE {i} ---\n\n{text}")
    return "".join(pieces)


def find_financial_section_flexible(text: str) -> str:
    """
    Locate financial statements in a document that may use either
    US 10-K headings or Canadian IFRS MD&A / interim report headings.
    Falls back to the existing SEC-focused finder, then to the tail 60%
    of the text when no markers match at all.
    """
    text_upper = text.upper()
    # Start searching ~15% in so we skip cover/TOC without being too
    # aggressive — Canadian quarterlies are shorter than 10-Ks.
    search_start = int(len(text) * 0.15)

    markers = [
        # US 10-K / 10-Q headings
        "CONSOLIDATED STATEMENTS OF OPERATIONS",
        "CONSOLIDATED STATEMENTS OF INCOME",
        "CONSOLIDATED BALANCE SHEET",
        "CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME",
        "CONSOLIDATED STATEMENTS OF CASH FLOW",
        # Canadian IFRS headings
        "INTERIM CONDENSED CONSOLIDATED STATEMENTS OF INCOME",
        "INTERIM CONSOLIDATED STATEMENTS OF INCOME",
        "CONDENSED INTERIM CONSOLIDATED STATEMENTS OF INCOME",
        "INTERIM CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME",
        "INTERIM CONSOLIDATED BALANCE SHEET",
        "INTERIM CONSOLIDATED STATEMENTS OF CASH FLOW",
        "STATEMENTS OF FINANCIAL POSITION",
        # Either-or
        "MANAGEMENT'S DISCUSSION AND ANALYSIS",
        "MANAGEMENTS DISCUSSION AND ANALYSIS",
    ]

    best_pos = len(text)
    for marker in markers:
        pos = text_upper.find(marker, search_start)
        if 0 < pos < best_pos:
            best_pos = pos

    if best_pos >= len(text):
        return text[int(len(text) * 0.40):]

    return text[best_pos: best_pos + 120_000]


def extract_metrics_from_pdf(
    filing_path: Path,
    period: str,
    reporting_units: str | None = None,
) -> dict[str, Any]:
    """
    Full pipeline for PDF-based financial filings (Canadian quarterly
    reports, annual reports, MD&A, or any uploaded non-mining PDF):
    PDF -> text -> financial section -> chunks -> Claude -> merged metrics.

    Uses the same `SYSTEM_PROMPT` as the HTM pipeline, so the 12
    standard financial metrics are extracted with identical semantics.

    `reporting_units` is an optional CLI-supplied override ('thousands' or
    'millions') that bypasses autodetection. The escape hatch matters
    because Canadian IFRS interim reports sometimes use unit phrases
    (e.g. "all amounts rounded to the nearest thousand") that the
    detector's regex library doesn't yet cover.
    """
    filing_path = Path(filing_path)
    print(f"  Extracting text from {filing_path.name}...")
    full_text = extract_text_from_pdf(filing_path)
    print(f"  Full text length: {len(full_text):,} chars")

    # Strip the page-break scaffolding ("--- PAGE N ---") before deciding
    # whether the PDF actually yielded any content — an image-only PDF
    # still produces those markers even though there's no real text.
    real_text = re.sub(r"--- PAGE \d+ ---", "", full_text).strip()
    if not real_text:
        print("  WARNING: PDF yielded no text — likely a scanned image. Skipping.")
        return {m: None for m in METRICS_TO_EXTRACT}

    financial_section = find_financial_section_flexible(full_text)
    print(f"  Financial section: {len(financial_section):,} chars")

    # Scan the FULL document when autodetecting units because Canadian IFRS
    # reports declare '(thousands of United States dollars)' in the repeated
    # table headers, many of which live well past the 120k-char financial
    # section slice.
    unit_hint = detect_reporting_unit(full_text, override=reporting_units)
    print(f"  Units: {unit_hint[:80]}...")

    chunks = chunk_text(financial_section)
    print(f"  Sending {len(chunks)} chunk(s) to Claude...")

    results: list[dict[str, Any]] = []
    for i, chunk in enumerate(chunks):
        print(f"    Chunk {i + 1}/{len(chunks)}...", end=" ", flush=True)
        try:
            annotated_chunk = f"{unit_hint}\n\n{chunk}"
            metrics = extract_metrics_from_chunk(annotated_chunk)
            results.append(metrics)
            merged_so_far = merge_metrics(results)
            found = sum(1 for v in merged_so_far.values() if v is not None)
            print(f"{found}/{len(METRICS_TO_EXTRACT)} metrics found")
            if found == len(METRICS_TO_EXTRACT):
                break
        except Exception as e:
            print(f"ERROR: {e}")
            results.append({})

    return merge_metrics(results)


def extract_metrics(
    filing_path: Path,
    period: str,
    reporting_units: str | None = None,
) -> dict[str, Any]:
    """
    Full pipeline: HTM file -> text -> chunks -> Claude -> merged metrics.

    `reporting_units` optionally overrides the autodetected unit scale. See
    `extract_metrics_from_pdf` for rationale.
    """
    print(f"  Extracting text from {filing_path.name}...")
    full_text = extract_text_from_htm(filing_path)
    print(f"  Full text length: {len(full_text):,} chars")

    financial_section = find_financial_section(full_text)
    print(f"  Financial section: {len(financial_section):,} chars")

    # Autodetect on the full document so unit declarations buried in 10-K
    # footnotes still register, then allow CLI override.
    unit_hint = detect_reporting_unit(full_text, override=reporting_units)
    print(f"  Units: {unit_hint[:80]}...")

    chunks = chunk_text(financial_section)
    print(f"  Sending {len(chunks)} chunk(s) to Claude...")

    results = []
    for i, chunk in enumerate(chunks):
        print(f"    Chunk {i + 1}/{len(chunks)}...", end=" ", flush=True)
        try:
            # Prepend unit hint so Claude always knows how to scale
            annotated_chunk = f"{unit_hint}\n\n{chunk}"
            metrics = extract_metrics_from_chunk(annotated_chunk)
            results.append(metrics)
            merged_so_far = merge_metrics(results)
            found = sum(1 for v in merged_so_far.values() if v is not None)
            print(f"{found}/{len(METRICS_TO_EXTRACT)} metrics found")
            if found == len(METRICS_TO_EXTRACT):
                break
        except Exception as e:
            print(f"ERROR: {e}")
            results.append({})

    return merge_metrics(results)
