"""
fin_parser/extraction/claude_extractor.py
Phase 1 extraction: parse filing HTML, chunk it, send to Claude, get structured metrics back.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import anthropic

from fin_parser.config import ANTHROPIC_API_KEY, CLAUDE_MODEL

CLIENT = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

# Metrics we want Claude to extract
METRICS_TO_EXTRACT = [
    "revenue",
    "net_income",
    "eps_basic",
    "eps_diluted",
    "free_cash_flow",
    "operating_cash_flow",
    "shares_outstanding",
    "shares_diluted",
    "total_debt",
    "cash_and_equivalents",
    "goodwill",
    "capex",
]

SYSTEM_PROMPT = """
You are a financial analyst extracting data from SEC 10-K and 10-Q filings.
You will be given a section of a filing. Extract ONLY the metrics below and return a valid JSON object.
No preamble, no explanation, no markdown — just the JSON.

METRIC DEFINITIONS (be precise about which line item to use):

Income Statement:
- revenue: "Net sales" or "Total net revenue" — the top-line revenue figure. Do NOT use segment
  revenues that sum to a larger total. Use the single consolidated top-line figure.
- net_income: "Net income" attributable to the company (not including minority interest).
- eps_basic: "Basic" earnings per share as reported.
- eps_diluted: "Diluted" earnings per share as reported.

Cash Flow Statement:
- operating_cash_flow: "Net cash generated by operating activities" or equivalent.
- capex: "Payments for acquisition of property, plant and equipment" — always return as a
  POSITIVE number even if shown as negative in the filing.
- free_cash_flow: operating_cash_flow minus capex. Compute this yourself if both are present.

Balance Sheet:
- cash_and_equivalents: "Cash and cash equivalents" only — do NOT include marketable securities.
- total_debt: Sum of "Term debt, current portion" + "Term debt, non-current" (long-term debt).
  Do NOT include lease obligations or accounts payable.
- goodwill: "Goodwill" as reported on the balance sheet.

Share Data:
- shares_outstanding: Basic weighted-average shares used in EPS calculation (in millions).
- shares_diluted: Diluted weighted-average shares used in EPS calculation (in millions).

RULES:
- All monetary values in millions of USD. If the filing reports in thousands, divide by 1000.
  If reported in billions, multiply by 1000.
- Share counts in millions.
- EPS in dollars as reported — do not scale.
- Use ONLY the most recent fiscal year / annual period if multiple years are shown.
- If a metric cannot be found in this chunk, set it to null.
- Never guess or estimate — only extract values explicitly stated in the text.

OUTPUT FORMAT (return exactly this structure):
{
  "revenue": 391035,
  "net_income": 93736,
  "eps_basic": 6.14,
  "eps_diluted": 6.11,
  "free_cash_flow": 99584,
  "operating_cash_flow": 110543,
  "shares_outstanding": 15439,
  "shares_diluted": 15550,
  "total_debt": 95281,
  "cash_and_equivalents": 29965,
  "goodwill": 72609,
  "capex": 10959
}
""".strip()


def extract_text_from_htm(path: Path) -> str:
    """
    Strip HTML tags from a filing and return plain text.
    Focuses on the financial statements section.
    """
    raw = path.read_text(encoding="utf-8", errors="ignore")

    # Remove scripts and styles
    raw = re.sub(r"<script[^>]*>.*?</script>", " ", raw, flags=re.DOTALL | re.IGNORECASE)
    raw = re.sub(r"<style[^>]*>.*?</style>", " ", raw, flags=re.DOTALL | re.IGNORECASE)

    # Remove all HTML tags
    text = re.sub(r"<[^>]+>", " ", raw)

    # Collapse whitespace
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()


def find_financial_section(text: str) -> str:
    """
    Isolate the financial statements section from the full filing text.
    Skips the table of contents by finding the SECOND occurrence of key markers,
    or by looking past the first 20% of the document.
    """
    text_upper = text.upper()
    # Skip the first 20% of the doc (TOC + boilerplate)
    search_start = len(text) // 5

    markers = [
        "CONSOLIDATED STATEMENTS OF OPERATIONS",
        "CONSOLIDATED STATEMENTS OF INCOME",
        "CONSOLIDATED BALANCE SHEET",
        "CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME",
        "NOTES TO CONSOLIDATED FINANCIAL STATEMENTS",
    ]

    best_pos = len(text)
    for marker in markers:
        pos = text_upper.find(marker, search_start)
        if 0 < pos < best_pos:
            best_pos = pos

    if best_pos < len(text):
        return text[best_pos: best_pos + 120_000]

    # Fallback: second half of document
    return text[len(text) // 2:]


def chunk_text(text: str, chunk_size: int = 12_000, overlap: int = 500) -> list[str]:
    """Split text into overlapping chunks to stay within Claude's context."""
    chunks = []
    start = 0
    while start < len(text):
        end = start + chunk_size
        chunks.append(text[start:end])
        start = end - overlap
    return chunks


def extract_metrics_from_chunk(chunk: str) -> dict[str, Any]:
    """Send one chunk to Claude and return parsed metrics dict."""
    response = CLIENT.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=1000,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": chunk}],
    )
    raw = response.content[0].text.strip()

    # Strip markdown fences if Claude added them
    raw = re.sub(r"^```json\s*", "", raw)
    raw = re.sub(r"\s*```$", "", raw)

    return json.loads(raw)


def merge_metrics(results: list[dict[str, Any]]) -> dict[str, Any]:
    """
    Merge metrics across chunks — take the first non-null value for each metric.
    This handles cases where different metrics appear in different sections.
    """
    merged: dict[str, Any] = {m: None for m in METRICS_TO_EXTRACT}
    for result in results:
        for metric in METRICS_TO_EXTRACT:
            if merged[metric] is None and result.get(metric) is not None:
                merged[metric] = result[metric]
    return merged


def extract_metrics(filing_path: Path, period: str) -> dict[str, Any]:
    """
    Full pipeline: HTM file -> text -> chunks -> Claude -> merged metrics.

    Returns a dict of metric -> value (None if not found).
    """
    print(f"  Extracting text from {filing_path.name}...")
    full_text = extract_text_from_htm(filing_path)
    print(f"  Full text length: {len(full_text):,} chars")

    financial_section = find_financial_section(full_text)
    print(f"  Financial section: {len(financial_section):,} chars")

    chunks = chunk_text(financial_section)
    print(f"  Sending {len(chunks)} chunk(s) to Claude...")

    results = []
    for i, chunk in enumerate(chunks):
        print(f"    Chunk {i + 1}/{len(chunks)}...", end=" ", flush=True)
        try:
            metrics = extract_metrics_from_chunk(chunk)
            results.append(metrics)
            # Stop early if we already have all metrics
            merged_so_far = merge_metrics(results)
            found = sum(1 for v in merged_so_far.values() if v is not None)
            print(f"{found}/{len(METRICS_TO_EXTRACT)} metrics found")
            if found == len(METRICS_TO_EXTRACT):
                break
        except Exception as e:
            print(f"ERROR: {e}")
            results.append({})

    return merge_metrics(results)
